### ISSUE TITLE
Translate subcategories names and other texts

### ISSUE THREAD

**Issue by smellai** [arduino/reference-ko#2]
- Arduino Reference
- The Arduino programming language Reference, organized into Functions, Variable and Constant, and Structure keywords.
- functions
- For controlling the Arduino board and performing computations.
- Digital I/O
- Analog I/O
- Zero, Due & MKR Family
- Advanced I/O
- Time
- Math
- Trigonometry
- Characters
- Random Numbers
- Bits and Bytes
- External Interrupts
- Interrupts
- Communication
- Serial
- Stream
- USB
- Keyboard
- Mouse
- variables
- Arduino data types and constants.
- Constants
- Conversion
- Data Types
- Variable Scope & Qualifiers
- Utilities
- structure
- The elements of Arduino (C++) code.
- Sketch
- Control Structure
- Further Syntax
- Arithmetic Operators
- Comparison Operators
- Boolean Operators
- Pointer Access Operators
- Bitwise Operators
- Compound Operators

**Comment by sebuls** [comment]
Do I have to translate these too?

**Comment by smellai** [comment]
Yes please, you can write them here in a comment and I will integrate them. Please notice that in every adoc file you should translate the 'subCategories' tag to match with the terms in this list. I'll let your PR open waiting for this edit, ok? Thanks for pushing a PR with all the files together! <3

**Comment by sebuls** [comment]
Can you intergrate them? Thank you very much. Help me please.
Korean translations are as follows.

아두이노 참조
함수, 변수 및 상수, 구조 키워드로 구성된 아두이노 프로그래밍 언어 참조.
함수
아두이노 보드를 제어하고 계산을 수행하기 위하여.
디지털 입출력
아날로그 입출력
제로, 두에 및 MKR 제품군
고급 입출력
시간
수학
삼각법
문자
난수
비트 및 바이트
외부 인터럽트
인터럽트
통신
시리얼
스트림
USB
키보드
마우스
변수
아두이노 자료형 및 상수.
상수
변환
자료형
가변 범위 및 한정어
유틸리티
구조
아두이노 (C ++) 코드의 요소.
스케치
제어 구조
추가 문법
산술 연산자
비교 연산자
부울 연산자
포인터 액세스 연산자
비트 연산자
복합 연산자

**Comment by smellai** [comment]
Here your translations:
https://reference.arduino.cc/reference/ko/

As soon as we add translated pages that use the corresponding subcategory tag, links will appear under the related subcategory.
Thanks!
