### ISSUE TITLE
Translate Site texts

### ISSUE THREAD

**Issue by smellai** [arduino/reference-ko#3]
- id: pageTitle
  translation: Language Reference

- id: pageDescription
  translation: "Arduino programming language can be divided in three main parts: structure, values (variables and constants), and functions."

- id: language
  translation: Language

- id: functions
  translation: functions

- id: variables
  translation: variables

- id: structure
  translation: structure

- id: libraries
  translation: Libraries

- id: glossary
  translation: Glossary

- id: editButton
  translation: Edit This Page

- id: license
  translation: "The Arduino Reference text is licensed under a <a href=\"https://creativecommons.org/licenses/by-sa/3.0/\" target=\"_blank\" rel=\"noopener\">Creative Commons Attribution-Share Alike 3.0 License</a>."

- id: githubLink
  translation: "Find anything that can be improved? <a href=\"https://github.com/arduino/reference-en\" target=\"_blank\" rel=\"noopener\">Suggest corrections and new documentation via GitHub.</a>"

- id: tutorialLink
  translation: "Doubts on how to use Github? Learn everything you need to know in <a href=\"https://create.arduino.cc/projecthub/Arduino_Genuino/contribute-to-the-arduino-reference-af7c37\" target=\"_blank\" rel=\"noopener\">this tutorial</a>."

**Comment by sebuls** [comment]
In progress

**Comment by sebuls** [comment]
id: pageDescription
translation: "Arduino programming language can be divided in three main parts: structure, values (variables and constants), and functions."

Translation:
"아두이노 프로그래밍 언어는 3부분으로 나눌 수 있다 : 구조, 값(변수와 상수), 그리고 함수."

**Comment by smellai** [comment]
No need to translate id, just value of 'Translation'. As follows:

id: pageDescription
Translation:
"아두이노 프로그래밍 언어는 3개 주요 부분으로 나눌 수 있다 : 구조, 값(변수와 상수), 그리고 함수."

**Comment by sebuls** [comment]
id: pageTitle
translation: 언어 참조

id: language
translation: 언어

id: functions
translation: 함수

id: variables
translation: 변수

id: structure
translation: 구조

id: libraries
translation: 라이브러리

id: glossary
translation: 용어 사전

id: editButton
translation: 이 페이지 편집
